apiVersion: v1
kind: Service
metadata:
  labels:
    name: checkshippingservice
  name: checkshippingservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8134
      # port listened at inside the container
      targetPort: 81034
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: checkshipping-ms
  type: NodePort