apiVersion: v1
kind: Service
metadata:
  labels:
    name: checkordertotalservice
  name: checkordertotalservice
spec:
  ports:
    # The port that this service should serve on.
    - port: 8102
      # port listened at inside the container
      targetPort: 8102
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: checkordertotal-ms
  type: NodePort