apiVersion: v1
kind: Pod
metadata:
  name: orderarbiter-ms
  labels:
    app: orderarbiter-ms
spec:
  nodeName: minikube
  containers:
  - name: orderarbiter
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/order-data-demo-devoxx"
    - name: APP_PORT
      value: "8128"
    - name: APP_HOME
      value: "order-workflow/OrderArbiter"
    - name: APP_STARTUP
      value: "OrderArbiter.js"
    - name: KAFKA_HOST
      value: "192.168.188.102"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8128
